version: '3.1'

services:
  
  sql1:
    build: ./Database
    hostname: sql1
    container_name: sql1
    environment:
      SA_PASSWORD: Mypassword123!
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    networks:
      - dc-backend
    volumes:
      - sqlvolume:/var/opt/mssql
    

  api:
    build: ./Backend
    image: aspnetapp
    container_name: myapp
    ports:
      - 8080:80
    networks: 
      - dc-backend
    depends_on:
      - sql1
    restart: on-failure

  react:
    build: ./Frontend
    image: react-app
    container_name: reactapp
    ports:
      - 80:80 

networks: 
  dc-backend:

volumes:
  sqlvolume: